## Invoice Status

### Imports and Library

In [1]:
import polars as pl
from data_source.make_dataset import load_gsheet_data
from data_source.sheet_ids import INVOICING,INVOICE_STATUS

In [2]:
async def load_invoice_status()->pl.LazyFrame:
    """Invoice status dataset"""
    df = await load_gsheet_data(INVOICING,INVOICE_STATUS)
    return df

In [7]:
def invoice_type_enum()->pl.Enum:
    """Invoice type enum"""
    list_of_invoice_type = [
        "oss",
        "sto",
        "si",
        "monthly"
    ]

    return pl.Enum(list_of_invoice_type)

In [14]:
invoice = await load_invoice_status()
open_invoice = invoice.select(
    pl.col("Month").alias("month"),
    pl.col('Report Type').cast(invoice_type_enum()).alias("type"),
    pl.col("Report Name").str.replace(" - OSS","").alias("name"),
    pl.col("ShipOwner").alias("customer"),
    pl.col("Starting Date").str.to_date(format="%d/%m/%Y").alias("start_date"),
    pl.col("Ending Date").str.to_date(format="%d/%m/%Y",strict=False).alias("end_date"),
    pl.col("Status").alias("status")
).filter(pl.col("status").ne(pl.lit("Closed")))

In [36]:
open_invoice.filter(pl.col("type").eq(pl.lit("oss"))).collect()

shape: (45, 7)
┌──────────┬──────┬──────────────┬────────────┬────────────┬────────────┬───────────┐
│ month    ┆ type ┆ name         ┆ customer   ┆ start_date ┆ end_date   ┆ status    │
│ ---      ┆ ---  ┆ ---          ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│ str      ┆ enum ┆ str          ┆ str        ┆ date       ┆ date       ┆ str       │
╞══════════╪══════╪══════════════╪════════════╪════════════╪════════════╪═══════════╡
│ May '25  ┆ oss  ┆ ATERPE ALAI  ┆ MAERSKLINE ┆ 2025-04-28 ┆ 2025-05-01 ┆ Not Ready │
│ May '25  ┆ oss  ┆ ECHEBASTAR   ┆ MAERSKLINE ┆ 2025-05-01 ┆ 2025-05-31 ┆ Not Ready │
│ May '25  ┆ oss  ┆ INPESCA      ┆ MAERSKLINE ┆ 2025-05-01 ┆ 2025-05-31 ┆ Not Ready │
│ May '25  ┆ oss  ┆ ISLAND CATCH ┆ MAERSKLINE ┆ 2025-05-01 ┆ 2025-05-31 ┆ Not Ready │
│ May '25  ┆ oss  ┆ OCEAN BASKET ┆ MAERSKLINE ┆ 2025-05-01 ┆ 2025-05-31 ┆ Not Ready │
│ …        ┆ …    ┆ …            ┆ …          ┆ …          ┆ …          ┆ …         │
│ July '25 ┆ oss  ┆ ECHEBASTAR   ┆ MAERSKLINE ┆ 2025-07-01 ┆ 2025-07-31 ┆ Not Ready │
│ July '25 ┆ oss  ┆ ALAKRANA     ┆ MAERSKLINE ┆ 2025-07-16 ┆ null       ┆ Not Ready │
│ July '25 ┆ oss  ┆ NOUR         ┆ MAERSKLINE ┆ 2025-07-15 ┆ 2025-07-18 ┆ Not Ready │
│ July '25 ┆ oss  ┆ JAI ALAI     ┆ MAERSKLINE ┆ 2025-07-18 ┆ null       ┆ Not Ready │
│ July '25 ┆ oss  ┆ TXORI TOKI   ┆ MAERSKLINE ┆ 2025-07-17 ┆ null       ┆ Not Ready │
└──────────┴──────┴──────────────┴────────────┴────────────┴────────────┴───────────┘

In [37]:
from dataframe.stuffing import coa
from datetime import date

"ATERPE ALAI"	"MAERSKLINE"	2025-04-28	2025-05-01

In [48]:
client_name = "ATERPE ALAI"
start_date = date(year=2025,month=4,day=28)
end_date = date(year=2025,month=5,day=1)

In [50]:
msk_plugin = await coa()
msk_plugin.collect().filter(pl.col("vessel_client").eq(client_name).and_(
    pl.col("date_plugged").is_between(start_date,end_date)
))

shape: (13, 18)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ vessel_cli ┆ customer   ┆ date_plugg ┆ time_plug ┆ … ┆ monitorin ┆ electrici ┆ total_ele ┆ total │
│ ent        ┆ ---        ┆ ed         ┆ ged       ┆   ┆ g_price   ┆ ty_unit_p ┆ ctricity  ┆ ---   │
│ ---        ┆ enum       ┆ ---        ┆ ---       ┆   ┆ ---       ┆ rice      ┆ ---       ┆ f64   │
│ str        ┆            ┆ date       ┆ time      ┆   ┆ f64       ┆ ---       ┆ f64       ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆ f64       ┆           ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ ATERPE     ┆ MAERSKLINE ┆ 2025-04-29 ┆ 22:29:00  ┆ … ┆ 30.0      ┆ 110.0     ┆ 880.0     ┆ 935.0 │
│ ALAI       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ ATERPE     ┆ MAERSKLINE ┆ 2025-04-29 ┆ 20:05:00  ┆ … ┆ 30.0      ┆ 110.0     ┆ 880.0     ┆ 935.0 │
│ ALAI       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ ATERPE     ┆ MAERSKLINE ┆ 2025-04-29 ┆ 20:19:00  ┆ … ┆ 30.0      ┆ 110.0     ┆ 880.0     ┆ 935.0 │
│ ALAI       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ ATERPE     ┆ MAERSKLINE ┆ 2025-04-29 ┆ 20:00:00  ┆ … ┆ 30.0      ┆ 110.0     ┆ 880.0     ┆ 935.0 │
│ ALAI       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ ATERPE     ┆ MAERSKLINE ┆ 2025-04-30 ┆ 12:23:00  ┆ … ┆ 30.0      ┆ 70.0      ┆ 490.0     ┆ 545.0 │
│ ALAI       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …     │
│ ATERPE     ┆ MAERSKLINE ┆ 2025-04-30 ┆ 19:20:00  ┆ … ┆ 0.0       ┆ 70.0      ┆ 70.0      ┆ 95.0  │
│ ALAI       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ ATERPE     ┆ MAERSKLINE ┆ 2025-04-30 ┆ 12:21:00  ┆ … ┆ 30.0      ┆ 70.0      ┆ 490.0     ┆ 545.0 │
│ ALAI       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ ATERPE     ┆ MAERSKLINE ┆ 2025-05-01 ┆ 10:25:00  ┆ … ┆ 30.0      ┆ 70.0      ┆ 420.0     ┆ 475.0 │
│ ALAI       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ ATERPE     ┆ MAERSKLINE ┆ 2025-05-01 ┆ 10:25:00  ┆ … ┆ 30.0      ┆ 70.0      ┆ 420.0     ┆ 475.0 │
│ ALAI       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ ATERPE     ┆ MAERSKLINE ┆ 2025-05-01 ┆ 12:25:00  ┆ … ┆ 0.0       ┆ 70.0      ┆ 420.0     ┆ 445.0 │
│ ALAI       ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

In [22]:
from dataframe.transport import transfer

In [24]:
msk_transfer = await transfer()
msk_transfer.filter(pl.col("remarks").eq(pl.lit("MAERSKLINE")).and_(
    pl.col("status").eq(pl.lit("Full"))
)).collect()

/tmp/ipykernel_362378/4002768550.py:4: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  )).collect()

shape: (4_900, 16)
┌──────────┬────────────┬─────────────┬────────┬───┬──────┬────────────┬─────────────┬─────────────┐
│ day_name ┆ date       ┆ container_n ┆ line   ┆ … ┆ size ┆ remarks    ┆ shifting_pr ┆ haulage_pri │
│ ---      ┆ ---        ┆ umber       ┆ ---    ┆   ┆ ---  ┆ ---        ┆ ice         ┆ ce          │
│ enum     ┆ date       ┆ ---         ┆ enum   ┆   ┆ enum ┆ str        ┆ ---         ┆ ---         │
│          ┆            ┆ enum        ┆        ┆   ┆      ┆            ┆ f64         ┆ f64         │
╞══════════╪════════════╪═════════════╪════════╪═══╪══════╪════════════╪═════════════╪═════════════╡
│ Tue      ┆ 2024-01-09 ┆ MNBU0404650 ┆ MAERSK ┆ … ┆ 40'  ┆ MAERSKLINE ┆ 0.0         ┆ 90.0        │
│ Tue      ┆ 2024-01-09 ┆ MSFU8626370 ┆ MAERSK ┆ … ┆ 40'  ┆ MAERSKLINE ┆ 0.0         ┆ 90.0        │
│ Tue      ┆ 2024-01-09 ┆ MSFU0002546 ┆ MAERSK ┆ … ┆ 40'  ┆ MAERSKLINE ┆ 0.0         ┆ 90.0        │
│ Tue      ┆ 2024-01-09 ┆ MNBU9070194 ┆ MAERSK ┆ … ┆ 40'  ┆ MAERSKLINE ┆ 0.0         ┆ 90.0        │
│ Tue      ┆ 2024-01-09 ┆ MNBU4156119 ┆ MAERSK ┆ … ┆ 40'  ┆ MAERSKLINE ┆ 0.0         ┆ 90.0        │
│ …        ┆ …          ┆ …           ┆ …      ┆ … ┆ …    ┆ …          ┆ …           ┆ …           │
│ Tue      ┆ 2025-07-22 ┆ SUDU6037140 ┆ MAERSK ┆ … ┆ 40'  ┆ MAERSKLINE ┆ 0.0         ┆ 90.0        │
│ Tue      ┆ 2025-07-22 ┆ MWCU5278860 ┆ MAERSK ┆ … ┆ 40'  ┆ MAERSKLINE ┆ 0.0         ┆ 90.0        │
│ Tue      ┆ 2025-07-22 ┆ SUDU8031666 ┆ MAERSK ┆ … ┆ 40'  ┆ MAERSKLINE ┆ 0.0         ┆ 90.0        │
│ Tue      ┆ 2025-07-22 ┆ MNBU0087107 ┆ MAERSK ┆ … ┆ 40'  ┆ MAERSKLINE ┆ 0.0         ┆ 90.0        │
│ Tue      ┆ 2025-07-22 ┆ MSFU0004261 ┆ MAERSK ┆ … ┆ 40'  ┆ MAERSKLINE ┆ 0.0         ┆ 90.0        │
└──────────┴────────────┴─────────────┴────────┴───┴──────┴────────────┴─────────────┴─────────────┘