In [ ]:
import polars as pl

from dataframe.emr import pti, washing, shifting
from dataframe.bin_dispatch import full_scows, empty_scows
from dataframe.miscellaneous import (
    cccs_stuffing,
    by_catch,
    cross_stuffing,
    dispatch_to_cargo,
)
from dataframe.transport import scow_transfer

from type_casting.dates import DayName, UPPER_BOUND, UPPER_BOUND_SPECIAL_DAY
from type_casting.validations import MovementType, Overtime, OvertimePerc
from data.price import get_price

## Miscellaneous

In [7]:
stuffing = await cccs_stuffing()

stuffing.filter(pl.col("date").dt.year().eq(2025)).group_by(
    pl.col("date").dt.month(), maintain_order=True
).agg(
    pl.col("total_tonnage").sum().alias("Total Tonnage Stuffed"),
    pl.col("total_price").sum().alias("CCCS Stuffing"),
).collect()

/tmp/ipykernel_362382/2378580964.py:8: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  ).collect()

shape: (7, 3)
┌──────┬───────────────────────┬───────────────┐
│ date ┆ Total Tonnage Stuffed ┆ CCCS Stuffing │
│ ---  ┆ ---                   ┆ ---           │
│ i8   ┆ f64                   ┆ f64           │
╞══════╪═══════════════════════╪═══════════════╡
│ 1    ┆ 2783.029              ┆ 74127.638     │
│ 2    ┆ 1589.492              ┆ 42160.599     │
│ 3    ┆ 2634.261              ┆ 69891.5155    │
│ 4    ┆ 2559.173              ┆ 74317.0505    │
│ 5    ┆ 2502.916              ┆ 66567.7615    │
│ 6    ┆ 1674.419              ┆ 44373.633     │
│ 7    ┆ 1430.082              ┆ 37830.6615    │
└──────┴───────────────────────┴───────────────┘

In [8]:
by_catch_ = await by_catch()
by_catch_.collect()

/tmp/ipykernel_362382/3997880446.py:2: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  by_catch_.collect()

shape: (2_286, 9)
┌──────┬────────────┬─────────────┬─────────────┬───┬────────────┬────────────┬───────┬────────────┐
│ day  ┆ date       ┆ customer    ┆ vessel      ┆ … ┆ total_tonn ┆ overtime_t ┆ Price ┆ total_pric │
│ ---  ┆ ---        ┆ ---         ┆ ---         ┆   ┆ age        ┆ onnage     ┆ ---   ┆ e          │
│ enum ┆ date       ┆ str         ┆ str         ┆   ┆ ---        ┆ ---        ┆ f64   ┆ ---        │
│      ┆            ┆             ┆             ┆   ┆ f64        ┆ f64        ┆       ┆ f64        │
╞══════╪════════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪═══════╪════════════╡
│ PH   ┆ 2023-11-01 ┆ OCEAN       ┆ CAP SAINT   ┆ … ┆ 12.214     ┆ 7.347      ┆ 2.5   ┆ 54.98625   │
│      ┆            ┆ BASKET      ┆ VINCENT     ┆   ┆            ┆            ┆       ┆            │
│ PH   ┆ 2023-11-01 ┆ AMIRANTE    ┆ IZURDIA     ┆ … ┆ 4.426      ┆ 4.426      ┆ 2.5   ┆ 22.13      │
│ PH   ┆ 2023-11-01 ┆ AMIRANTE    ┆ ALBACORA    ┆ … ┆ 1.908      ┆ 0.0        ┆ 2.5   ┆ 7.155      │
│      ┆            ┆             ┆ UNO         ┆   ┆            ┆            ┆       ┆            │
│ PH   ┆ 2023-11-01 ┆ AMIRANTE    ┆ ALBATUN DOS ┆ … ┆ 27.721     ┆ 18.907     ┆ 2.5   ┆ 127.5875   │
│ PH   ┆ 2023-11-01 ┆ AMIRANTE    ┆ ELAI ALAI   ┆ … ┆ 9.537      ┆ 9.537      ┆ 2.5   ┆ 47.685     │
│ …    ┆ …          ┆ …           ┆ …           ┆ … ┆ …          ┆ …          ┆ …     ┆ …          │
│ Thu  ┆ 2025-07-24 ┆ AMIRANTE    ┆ ELAI ALAI   ┆ … ┆ 4.697      ┆ 4.697      ┆ 3.5   ┆ 24.65925   │
│ Thu  ┆ 2025-07-24 ┆ AMIRANTE    ┆ ALBACORA    ┆ … ┆ 10.652     ┆ 3.432      ┆ 3.5   ┆ 43.288     │
│      ┆            ┆             ┆ UNO         ┆   ┆            ┆            ┆       ┆            │
│ Thu  ┆ 2025-07-24 ┆ OCEAN       ┆ PLAYA DE    ┆ … ┆ 2.01       ┆ 2.01       ┆ 3.5   ┆ 10.5525    │
│      ┆            ┆ BASKET      ┆ RIS         ┆   ┆            ┆            ┆       ┆            │
│ Thu  ┆ 2025-07-24 ┆ AMIRANTE    ┆ ALBACAN     ┆ … ┆ 5.874      ┆ 5.874      ┆ 3.5   ┆ 30.8385    │
│ Thu  ┆ 2025-07-24 ┆ OCEAN       ┆ AVEL VAD    ┆ … ┆ 1.418      ┆ 0.0        ┆ 3.5   ┆ 4.963      │
│      ┆            ┆ BASKET      ┆             ┆   ┆            ┆            ┆       ┆            │
└──────┴────────────┴─────────────┴─────────────┴───┴────────────┴────────────┴───────┴────────────┘

## Washing PTI and Shifting

In [ ]:
container_washing = await washing()


container_washing = (
    container_washing.filter(pl.col("invoice_to").ne(pl.lit("INVALID")))
    .filter(pl.col("date").dt.year().eq(2025))
    .group_by(pl.col("date").dt.month(), maintain_order=True)
    .agg(
        pl.len().alias("Number of Washing Records"),
        pl.col("price").sum().alias("Washing"),
    )
)

container_washing.collect()

shape: (7, 3)
┌──────┬───────────────────────────┬─────────┐
│ date ┆ Number of Washing Records ┆ Washing │
│ ---  ┆ ---                       ┆ ---     │
│ i8   ┆ u32                       ┆ i64     │
╞══════╪═══════════════════════════╪═════════╡
│ 1    ┆ 477                       ┆ 14310   │
│ 2    ┆ 315                       ┆ 9450    │
│ 3    ┆ 394                       ┆ 11820   │
│ 4    ┆ 405                       ┆ 12150   │
│ 5    ┆ 432                       ┆ 12960   │
│ 6    ┆ 275                       ┆ 8250    │
│ 7    ┆ 247                       ┆ 7410    │
└──────┴───────────────────────────┴─────────┘

### Shifting

In [ ]:
internal_shifting = await shifting()

internal_shifting = (
    internal_shifting.filter(pl.col("invoice_to").ne(pl.lit("INVALID")))
    .filter(pl.col("date").dt.year().eq(2025))
    .group_by(pl.col("date").dt.month(), maintain_order=True)
    .agg(
        pl.len().alias("Number of Shifing Records"),
        pl.col("price").sum().alias("Internal Shifting"),
    )
)

internal_shifting.collect()

shape: (7, 3)
┌──────┬───────────────────────────┬───────────────────┐
│ date ┆ Number of Shifing Records ┆ Internal Shifting │
│ ---  ┆ ---                       ┆ ---               │
│ i8   ┆ u32                       ┆ f64               │
╞══════╪═══════════════════════════╪═══════════════════╡
│ 1    ┆ 13                        ┆ 455.0             │
│ 2    ┆ 8                         ┆ 280.0             │
│ 3    ┆ 30                        ┆ 1050.0            │
│ 4    ┆ 5                         ┆ 175.0             │
│ 5    ┆ 19                        ┆ 665.0             │
│ 6    ┆ 11                        ┆ 385.0             │
│ 7    ┆ 11                        ┆ 385.0             │
└──────┴───────────────────────────┴───────────────────┘

## PTI Summary

In [ ]:
pre_trip_inspection = await pti()


pre_trip_inspection = pre_trip_inspection.group_by(
    pl.col("datetime_start").dt.month(), maintain_order=True
).agg(
    pl.len().alias("Number of PTI records"),
    pl.col("plugin_price").sum().alias("Plugin for PTI"),
    pl.col("shifting_price").sum().alias("Shifting for PTI"),
    pl.col("electricity_price").sum().alias("Electricity for PTI"),
    pl.col("total_price").sum().alias("PTI Total"),
)

pre_trip_inspection.collect()

shape: (7, 6)
┌────────────────┬───────────────┬────────────────┬──────────────────┬─────────────┬───────────┐
│ datetime_start ┆ Number of PTI ┆ Plugin for PTI ┆ Shifting for PTI ┆ Electricity ┆ PTI Total │
│ ---            ┆ records       ┆ ---            ┆ ---              ┆ for PTI     ┆ ---       │
│ i8             ┆ ---           ┆ f64            ┆ f64              ┆ ---         ┆ f64       │
│                ┆ u32           ┆                ┆                  ┆ f64         ┆           │
╞════════════════╪═══════════════╪════════════════╪══════════════════╪═════════════╪═══════════╡
│ 1              ┆ 534           ┆ 13350.0        ┆ 16870.0          ┆ 36025.0     ┆ 66245.0   │
│ 2              ┆ 356           ┆ 8900.0         ┆ 10815.0          ┆ 25905.0     ┆ 45620.0   │
│ 3              ┆ 442           ┆ 11050.0        ┆ 13020.0          ┆ 28060.0     ┆ 52130.0   │
│ 4              ┆ 504           ┆ 12600.0        ┆ 15050.0          ┆ 33505.0     ┆ 61155.0   │
│ 5              ┆ 429           ┆ 10725.0        ┆ 14000.0          ┆ 28845.0     ┆ 53570.0   │
│ 6              ┆ 384           ┆ 9600.0         ┆ 11655.0          ┆ 25140.0     ┆ 46395.0   │
│ 7              ┆ 256           ┆ 6400.0         ┆ 8540.0           ┆ 17140.0     ┆ 32080.0   │
└────────────────┴───────────────┴────────────────┴──────────────────┴─────────────┴───────────┘

## BIN TRANSFER

### Bin Dispath to /from IOT

In [ ]:
bin_dispatch_empty = await empty_scows()

bin_dispatch_empty.group_by(pl.col("date").dt.month(), maintain_order=True).agg(
    pl.col("num_of_scows").sum().alias("Number of Scow transferred"),
    pl.col("total_price").sum().alias("Empty Scow Transfer"),
).collect()

shape: (5, 3)
┌──────┬────────────────────────────┬─────────────────────┐
│ date ┆ Number of Scow transferred ┆ Empty Scow Transfer │
│ ---  ┆ ---                        ┆ ---                 │
│ i8   ┆ i64                        ┆ f64                 │
╞══════╪════════════════════════════╪═════════════════════╡
│ 1    ┆ 983                        ┆ 3440.5              │
│ 2    ┆ 910                        ┆ 3185.0              │
│ 3    ┆ 221                        ┆ 773.5               │
│ 4    ┆ 26                         ┆ 91.0                │
│ 6    ┆ 1122                       ┆ 3927.0              │
└──────┴────────────────────────────┴─────────────────────┘

In [ ]:
bin_dispatch_full = await full_scows()

bin_dispatch_full.group_by(pl.col("date").dt.month(), maintain_order=True).agg(
    pl.col("tonnage").sum().alias("Tonnage transferred"),
    pl.col("total_price").sum().alias("Full Scow Transfer"),
).collect()

shape: (6, 3)
┌──────┬─────────────────────┬────────────────────┐
│ date ┆ Tonnage transferred ┆ Full Scow Transfer │
│ ---  ┆ ---                 ┆ ---                │
│ i8   ┆ f64                 ┆ f64                │
╞══════╪═════════════════════╪════════════════════╡
│ 1    ┆ 741.348             ┆ 2594.718           │
│ 2    ┆ 411.148             ┆ 1470.196           │
│ 3    ┆ 61.614              ┆ 215.649001         │
│ 4    ┆ 137.357             ┆ 480.7495           │
│ 6    ┆ 671.726             ┆ 2351.041           │
│ 7    ┆ 22.913              ┆ 80.1955            │
└──────┴─────────────────────┴────────────────────┘

### Scow Handling (Forklift)

In [ ]:
price = await get_price()

forklift_price = price.filter(
    pl.col("Service").eq("Forklift Scow Handling")
).with_columns(Date=pl.col("Date").str.to_date(format="%d/%m/%Y"))


forklift_scow_handling = await scow_transfer()

forklift_scow_handling = (
    forklift_scow_handling.filter(pl.col("date").dt.year().eq(2025))
    .with_columns(
        month=("1/" + pl.col("date").dt.month().cast(pl.Utf8) + "/2025").str.to_date(),
        day_name=pl.when(pl.col("date").is_in(DayName.public_holiday_series()))
        .then(DayName.PH)
        .otherwise(pl.col("date").dt.to_string(format="%a"))
        .cast(pl.Enum(DayName.get_all())),
    )
    .with_columns(
        time=pl.when(pl.col("movement_type").eq(MovementType.delivery))
        .then(pl.col("time_in"))
        .otherwise(pl.col("time_out"))
    )
    .with_columns(service=pl.lit("Forklift Scow Handling"))
    .with_columns(
        overtime=pl.when(
            (pl.col("day_name").is_in(DayName.get_special_days())).and_(
                pl.col("time").gt(UPPER_BOUND_SPECIAL_DAY)
            )
        )
        .then(pl.lit(Overtime.overtime_200_text))
        .when(
            (pl.col("day_name").is_in(DayName.get_special_days())).or_(
                pl.col("time").gt(UPPER_BOUND)
            )
        )
        .then(pl.lit(Overtime.overtime_150_text))
        .otherwise(pl.lit(Overtime.normal_hour_text))
    )
    .join_asof(
        forklift_price,
        by_right="Service",
        by_left="service",
        right_on="Date",
        left_on="date",
        strategy="backward",
    )
    .with_columns(
        total_price=pl.when(pl.col("overtime").eq(Overtime.normal_hour_text))
        .then(pl.col("Price") * OvertimePerc.normal_hour * pl.col("num_of_scows"))
        .when(pl.col("overtime").eq(Overtime.overtime_150_text))
        .then(pl.col("Price") * OvertimePerc.overtime_150 * pl.col("num_of_scows"))
        .when(pl.col("overtime").eq(Overtime.overtime_200_text))
        .then(pl.col("Price") * OvertimePerc.overtime_200 * pl.col("num_of_scows"))
        .otherwise(pl.lit(0.0))
    )
    .group_by(["date", "status", "movement_type", "overtime"], maintain_order=True)
    .agg(
        pl.col("num_of_scows").sum(),
        pl.col("time_out").min(),
        pl.col("time_in").max(),
        pl.col("Price").last(),
        pl.col("total_price").sum(),
    )
)

In [ ]:
full_scow_handling = (
    forklift_scow_handling.filter(pl.col("status").eq(pl.lit("Full")))
    .group_by(pl.col("date").dt.month(), maintain_order=True)
    .agg(
        pl.col("num_of_scows").sum(),
        pl.col("total_price").sum().alias("Full Scow Handling w/Forklift"),
    )
)


full_scow_handling.collect()

/tmp/ipykernel_335723/2696636844.py:12: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  full_scow_handling.collect()

shape: (6, 3)
┌──────┬──────────────┬───────────────────────────────┐
│ date ┆ num_of_scows ┆ Full Scow Handling w/Forklift │
│ ---  ┆ ---          ┆ ---                           │
│ i8   ┆ i64          ┆ f64                           │
╞══════╪══════════════╪═══════════════════════════════╡
│ 1    ┆ 856          ┆ 5136.0                        │
│ 2    ┆ 429          ┆ 2652.0                        │
│ 3    ┆ 92           ┆ 552.0                         │
│ 4    ┆ 140          ┆ 840.0                         │
│ 6    ┆ 708          ┆ 4248.0                        │
│ 7    ┆ 26           ┆ 156.0                         │
└──────┴──────────────┴───────────────────────────────┘

In [ ]:
empty_scow_handling = (
    forklift_scow_handling.filter(pl.col("status").eq(pl.lit("Empty")))
    .group_by(pl.col("date").dt.month(), maintain_order=True)
    .agg(
        pl.col("num_of_scows").sum(),
        pl.col("total_price").sum().alias("Empty Scow Handling w/Forklift"),
    )
)


empty_scow_handling.collect()

/tmp/ipykernel_335723/2175451727.py:12: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  empty_scow_handling.collect()

shape: (5, 3)
┌──────┬──────────────┬────────────────────────────────┐
│ date ┆ num_of_scows ┆ Empty Scow Handling w/Forklift │
│ ---  ┆ ---          ┆ ---                            │
│ i8   ┆ i64          ┆ f64                            │
╞══════╪══════════════╪════════════════════════════════╡
│ 1    ┆ 983          ┆ 5898.0                         │
│ 2    ┆ 910          ┆ 5460.0                         │
│ 3    ┆ 221          ┆ 1326.0                         │
│ 4    ┆ 26           ┆ 156.0                          │
│ 6    ┆ 1122         ┆ 6732.0                         │
└──────┴──────────────┴────────────────────────────────┘

In [1]:
import polars as pl
import pretty_errors
from datetime import date

from dataframe import netlist, stuffing
# from data_source.make_dataset import load_gsheet_data
# from data_source.sheet_ids import STUFFING_SHEET_ID,plugin_sheet

pretty_errors.activate()

vessel_name = "TXORI ZURI"
start_date = date(2025, 2, 12)
end_date = date(2025, 2, 15)


wDATA = await netlist.oss()

stuffingData = await stuffing.coa()

wDATA.filter(
    pl.col("vessel").eq(pl.lit(vessel_name)),
    pl.col("date").is_between(start_date, end_date),
).join(
    stuffingData.with_columns(
        container_number=pl.col("container_number").cast(pl.Utf8)
    ),
    left_on=["date", "destination"],
    right_on=["date_plugged", "container_number"],
    how="left",
).select(
    pl.col("date").alias("Date"),
    pl.col("start_time"),
    pl.col("destination"),
    pl.col("plugged_status"),
    pl.col("storage_type"),
    pl.col("end_time"),
    pl.col("overtime"),
    pl.col("total_tonnage"),
    pl.col("Price"),
    pl.col("invoice_value"),
).collect()
# wDATA.collect()

sys:1: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided

shape: (29, 10)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────┬───────────┐
│ Date       ┆ start_time ┆ destinatio ┆ plugged_s ┆ … ┆ overtime  ┆ total_ton ┆ Price ┆ invoice_v │
│ ---        ┆ ---        ┆ n          ┆ tatus     ┆   ┆ ---       ┆ nage      ┆ ---   ┆ alue      │
│ date       ┆ time       ┆ ---        ┆ ---       ┆   ┆ str       ┆ ---       ┆ f64   ┆ ---       │
│            ┆            ┆ str        ┆ enum      ┆   ┆           ┆ f64       ┆       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════╪═══════════╡
│ 2025-02-12 ┆ 08:25:00   ┆ SUDU812440 ┆ Full      ┆ … ┆ normal    ┆ 26.94     ┆ 25.5  ┆ 686.97    │
│            ┆            ┆ 8          ┆           ┆   ┆ hours     ┆           ┆       ┆           │
│ 2025-02-12 ┆ 09:52:00   ┆ MNBU300960 ┆ Partial   ┆ … ┆ normal    ┆ 22.69     ┆ 25.5  ┆ 578.595   │
│            ┆            ┆ 1          ┆           ┆   ┆ hours     ┆           ┆       ┆           │
│ 2025-02-12 ┆ 10:13:00   ┆ TLLU116405 ┆ Full      ┆ … ┆ normal    ┆ 27.0      ┆ 25.5  ┆ 688.5     │
│            ┆            ┆ 2          ┆           ┆   ┆ hours     ┆           ┆       ┆           │
│ 2025-02-12 ┆ 11:33:00   ┆ MNBU366101 ┆ Full      ┆ … ┆ normal    ┆ 26.97     ┆ 25.5  ┆ 687.735   │
│            ┆            ┆ 3          ┆           ┆   ┆ hours     ┆           ┆       ┆           │
│ 2025-02-12 ┆ 12:02:00   ┆ MNBU368133 ┆ Full      ┆ … ┆ normal    ┆ 27.03     ┆ 25.5  ┆ 689.265   │
│            ┆            ┆ 9          ┆           ┆   ┆ hours     ┆           ┆       ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …     ┆ …         │
│ 2025-02-14 ┆ 09:57:00   ┆ MNBU916027 ┆ Completed ┆ … ┆ normal    ┆ 12.54     ┆ 25.5  ┆ 319.77    │
│            ┆            ┆ 7          ┆           ┆   ┆ hours     ┆           ┆       ┆           │
│ 2025-02-14 ┆ 09:57:00   ┆ SUDU625955 ┆ Full      ┆ … ┆ normal    ┆ 26.64     ┆ 25.5  ┆ 679.32    │
│            ┆            ┆ 4          ┆           ┆   ┆ hours     ┆           ┆       ┆           │
│ 2025-02-14 ┆ 11:24:00   ┆ MNBU377994 ┆ Full      ┆ … ┆ normal    ┆ 26.87     ┆ 25.5  ┆ 685.185   │
│            ┆            ┆ 2          ┆           ┆   ┆ hours     ┆           ┆       ┆           │
│ 2025-02-14 ┆ 16:20:00   ┆ MNBU040294 ┆ Partial   ┆ … ┆ normal    ┆ 10.117    ┆ 25.5  ┆ 257.9835  │
│            ┆            ┆ 0          ┆           ┆   ┆ hours     ┆           ┆       ┆           │
│ 2025-02-15 ┆ 09:49:00   ┆ MNBU040294 ┆ Completed ┆ … ┆ normal    ┆ 16.9      ┆ 25.5  ┆ 430.95    │
│            ┆            ┆ 0          ┆           ┆   ┆ hours     ┆           ┆       ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────┴───────────┘

In [2]:
stuffingData.filter(
    pl.col("vessel_client").eq(pl.lit(vessel_name)),
    pl.col("date_plugged").is_between(start_date, end_date),
    pl.col("operation_type").str.contains(pl.lit("OSS")),
).with_columns(
    date_plugged=pl.col("date_plugged").dt.combine(pl.col("time_plugged"))
).select(pl.col("date_plugged"), pl.col("container_number")).collect()

shape: (29, 2)
┌─────────────────────┬──────────────────┐
│ date_plugged        ┆ container_number │
│ ---                 ┆ ---              │
│ datetime[μs]        ┆ enum             │
╞═════════════════════╪══════════════════╡
│ 2025-02-12 16:10:00 ┆ MMAU1272939      │
│ 2025-02-12 14:36:00 ┆ MNBU3009601      │
│ 2025-02-12 15:05:00 ┆ MNBU3217626      │
│ 2025-02-12 13:23:00 ┆ MNBU3661013      │
│ 2025-02-12 13:53:00 ┆ MNBU3681339      │
│ …                   ┆ …                │
│ 2025-02-14 14:01:00 ┆ MNBU3779942      │
│ 2025-02-14 14:22:00 ┆ MNBU9160277      │
│ 2025-02-14 09:20:00 ┆ MWCU5261126      │
│ 2025-02-14 12:17:00 ┆ SUDU6259554      │
│ 2025-02-15 11:47:00 ┆ MNBU0402940      │
└─────────────────────┴──────────────────┘

In [3]:
from data.price import get_price

price = await get_price()

price.collect()

shape: (107, 3)
┌─────────────────────────────────┬───────┬────────────┐
│ Service                         ┆ Price ┆ Date       │
│ ---                             ┆ ---   ┆ ---        │
│ str                             ┆ f64   ┆ str        │
╞═════════════════════════════════╪═══════╪════════════╡
│ Additional Overtime             ┆ 7.5   ┆ 01/01/2023 │
│ Additional Overtime             ┆ 8.0   ┆ 01/03/2024 │
│ Basic OSS - Brine               ┆ 16.0  ┆ 01/01/2023 │
│ Basic OSS - Brine               ┆ 18.25 ┆ 01/03/2024 │
│ Basic OSS - Dry                 ┆ 30.5  ┆ 01/01/2023 │
│ …                               ┆ …     ┆ …          │
│ Loading to Container - Brine    ┆ 22.5  ┆ 01/01/2023 │
│ Loading to Container - Brine    ┆ 20.5  ┆ 01/03/2024 │
│ Loading to Container - Dry      ┆ 23.5  ┆ 01/01/2023 │
│ Loading to Container - Dry      ┆ 20.5  ┆ 01/03/2024 │
│ Container Stuffing with Forkli… ┆ 3.5   ┆ 01/03/2024 │
└─────────────────────────────────┴───────┴────────────┘

In [4]:
argi = "/home/garry-mounac/Dropbox/Crewing and Tally Clerk/Registers/2025/02 FEBRUARY 2025/REGISTER - 12.02.25.xlsm"

In [ ]:
pl.read_excel(argi, sheet_name="TXORI ARGI- 12.02.25").filter(
    pl.col("__UNNAMED__4").is_not_null(), pl.col("__UNNAMED__0").is_not_null()
).select(
    pl.col("__UNNAMED__0").alias("num"),
    pl.col("__UNNAMED__5")
    .str.replace("1899-12-31 ", "")
    .str.to_time(format="%H:%M:%S")
    .alias("end_time"),
).group_by(pl.col("end_time")).agg(pl.len().alias("num"))

shape: (2, 2)
┌──────────┬─────┐
│ end_time ┆ num │
│ ---      ┆ --- │
│ time     ┆ u32 │
╞══════════╪═════╡
│ 20:54:00 ┆ 31  │
│ 17:00:00 ┆ 32  │
└──────────┴─────┘

In [6]:
ops = "/home/garry-mounac/Dropbox/! OPERATION SUPPORTING DOCUMENTATION/2025/2025 IPHS operation activity.xlsx"

In [7]:
pl.read_excel(ops, sheet_name="HANDLING ACTIVITY").filter(
    pl.col("DATE").eq(date(2025, 2, 12)), pl.col("VESSEL NAME").eq(pl.lit("TXORI ARGI"))
).select(pl.col("Comments")).to_series().to_list()

['CCCS Front & Back / Extramen Sorting (12) + Well Support (10)']

In [2]:
import polars as pl
from dataframe import miscellaneous

await miscellaneous._cross_stuffing()